del /q /s *.dcu
del /q /s *.exe
del /q /s *.dll
del /q /s *.cbk
del /q /s *.drc
del /q /s *.dsk
del /q /s *.dsm
del /q /s *.rsm
del /q /s *.identcache
del /q /s *.local
del /q /s *.map
del /q /s *.ico
del /q /s *.otares
del /q /s *.stat
rmdir /Q /S .\__history
rmdir /Q /S .\__recovery
rmdir /Q /S Demo\FMX\__history
rmdir /Q /S Demo\Lazarus\__history
rmdir /Q /S Demo\VCL\__history
rmdir /Q /S Demo\VCL-QR-EPC\__history
rmdir /Q /S Demo\FMX\__recovery
rmdir /Q /S Demo\Lazarus\__recovery
rmdir /Q /S Demo\VCL\__recovery
rmdir /Q /S Demo\VCL-QR-EPC\__recovery
rmdir /Q /S Demo\VCL\Win32
rmdir /Q /S Demo\VCL\Win64
rmdir /Q /S Demo\VCL-QR-EPC\Win32
rmdir /Q /S Demo\VCL-QR-EPC\Win64
